id: A6628A436
base_file: fB25B.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 18:06:34.886864
  last_modified_at: 2022-06-19 18:06:34.886868
