id: A6628A436
base_file: f64BB.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - it
  - bo
  datatype: PlainText
  created_at: 2022-06-19 18:06:34.885022
  last_modified_at: 2022-06-19 18:06:34.885031
